//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryPublish.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_DL_Get063DocsForPublish_WithDate")]
        public string sProc {
            get {
                return ((string)(this["sProc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_DL_RPT_TodaysDocs_ByDate")]
        public string rptAdded {
            get {
                return ((string)(this["rptAdded"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_DL_RPT_MissedDocs")]
        public string rptMissed {
            get {
                return ((string)(this["rptMissed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_DL_RPT_Published_ByDate")]
        public string rptPub {
            get {
                return ((string)(this["rptPub"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plandocs-{0}-Changes.xls")]
        public string rptNameAdded {
            get {
                return ((string)(this["rptNameAdded"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plandocs-{0}-Missed.xls")]
        public string rptNameMissed {
            get {
                return ((string)(this["rptNameMissed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plandocs-{0}-Published.xls")]
        public string rptNamePub {
            get {
                return ((string)(this["rptNamePub"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_DL_Get063DocsForPublish_WithDate_Count")]
        public string sProcCount {
            get {
                return ((string)(this["sProcCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_DL_Get063DocsForPublish_WithDateForXLSX")]
        public string sProcForXLSX {
            get {
                return ((string)(this["sProcForXLSX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_DL_Get063DocsForPublish_WithDate_CountForXLSX")]
        public string sProcCountForXLSX {
            get {
                return ((string)(this["sProcCountForXLSX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=DBServer1;Database=PAILibraryCI;User ID=PAILibUser;Password=Lu$443!;Persis" +
            "t Security Info=True;Async=true;\r\n        Application Name=PAILIB_PUB")]
        public string conDBServer1 {
            get {
                return ((string)(this["conDBServer1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("schedjob@paisc.com;")]
        public string DevEmail {
            get {
                return ((string)(this["DevEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LB\\LibraryReports\\")]
        public string rptPath {
            get {
                return ((string)(this["rptPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LB\\LibraryReports\\LibraryLogs\\pailib_pub-{0}.log")]
        public string logPath {
            get {
                return ((string)(this["logPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LB\\LibraryReports\\LibraryPublish\\")]
        public string pubPath {
            get {
                return ((string)(this["pubPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LB\\library\\")]
        public string libPath {
            get {
                return ((string)(this["libPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LB\\LibraryReports\\LibraryLogs\\pailib_pub-{0}_err.log")]
        public string errLogPath {
            get {
                return ((string)(this["errLogPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LB\\LibraryReports\\LibraryPublishHealthX\\")]
        public string pubPathHealthX {
            get {
                return ((string)(this["pubPathHealthX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LB\\LibraryReports\\LibraryPublishQBL\\")]
        public string pubPathQBL {
            get {
                return ((string)(this["pubPathQBL"]));
            }
        }
    }
}
